### ISSUE TITLE
Add utility pallet

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/chainbridge-substrate-chain#37]
## Story
As a developer
I want be able to dispatch a batch of transactions
So that I can setup the chain configuration easily

## Background
[These instructions](https://polkadot.js.org/docs/api/cookbook/tx#how-can-i-batch-transactions) require [this pallet](https://github.com/paritytech/substrate/tree/master/frame/utility) to be included in the runtime.

## Details
N/A

## Scenarios
N/A

## Implementation details
N.A

## Testing details
N/A

## Acceptance criteria
Utility pallet is included in the runtime and available for usage.

**Comment by P1sar** [comment]
closing due to non relevance
